# Podfile for WebRTC Dialer

platform :ios, '15.0'
use_frameworks!

target 'WebRTCDialer' do
  # WebRTC - Core library for peer-to-peer calling
  pod 'GoogleWebRTC', '~> 1.1.31999'

  # Socket.IO - WebSocket client for signaling
  pod 'Socket.IO-Client-Swift', '~> 16.0.1'

  # PhoneNumberKit - Phone number parsing and validation
  pod 'PhoneNumberKit', '~> 3.7.4'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'

      # Disable bitcode (WebRTC doesn't support it)
      config.build_settings['ENABLE_BITCODE'] = 'NO'

      # Optimize for Swift
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        config.build_settings['CODE_SIGN_IDENTITY'] = ''
      end
    end
  end
end
